Update component to use new versions of text, avatar, stack and foundations
selsa-inube/inubekit-user pull request #3
Opened 2024-03-05 10:11 UTC by JanuarAsprilla

here the component is re-factored to use the new version of avatar, stack and foundations

2024-03-05 15:10 UTC, cmarin001 requested changes

2024-03-05 15:10 UTC, cmarin001 commented on src/User/index.tsx
>  export interface IUserProps {
It would be preferable to rename it simply as IUser.

2024-03-05 17:07 UTC, wfercanas requested changes

2024-03-05 17:07 UTC, wfercanas commented on package.json
>      "@inubekit/stack": "^1.1.0",
Install latest version of `stack`

2024-03-05 17:07 UTC, wfercanas commented on src/User/index.tsx
> +          gap="8px"
This gap should be of `4px`

2024-03-05 19:24 UTC, JanuarAsprilla commented on package.json
>      "@inubekit/stack": "^1.1.0",
solved

2024-03-05 19:55 UTC, cmarin001 requested changes

2024-03-05 19:55 UTC, cmarin001 commented on src/User/index.tsx
> +export interface IUser {
The export statement for this interface needs to be positioned at the end of the file, and it should be formatted as follows: export type { IUser }

2024-03-05 19:56 UTC, cmarin001 requested changes

2024-03-05 19:56 UTC, cmarin001 commented on src/User/User.stories.tsx
> +export const Default = (args: IUser) => <User {...args} />;
the export should be at the end of the file

2024-03-05 20:06 UTC, JanuarAsprilla commented on src/User/index.tsx
> +export interface IUser {
solved

2024-03-06 14:23 UTC, wfercanas commented on package.json
>      "@inubekit/stack": "^1.1.0",
The package.json still does the installation of stack v1.1.0, while the lastest version of the component is v2.0.0

2024-03-06 15:09 UTC, JanuarAsprilla commented on package.json
>      "@inubekit/stack": "^1.1.0",
solved

2024-03-06 20:18 UTC, wfercanas approved these changes

2024-03-06 20:19 UTC, merged