Add clickable Avatar with floating menu in User component
selsa-inube/inubekit-user pull request #39
Opened 2024-10-01 17:45 UTC by cmarin001

This PR updates the Avatar component to make it clickable by adding support for an onClick prop. The User component has been extended to toggle a floating Menu when the Avatar is clicked. The Menu is positioned below and aligned to the left of the Avatar, providing a better user interaction experience. Updates also include adjustments to the StyledUserContainer and StyledMenuContainer to ensure proper alignment and floating behavior of the Menu. Destructuring of props has been implemented within the function body in the Avatar component, as requested for consistency with the code style.

2024-10-04 22:57 UTC, wfercanas requested changes

2024-10-04 22:57 UTC, wfercanas commented on src/User/User.stories.tsx
> +        onClick: () => console.log("Logged out"),
Use the property `action` just like you did in nav, so that we have consistent interfaces in similar components.

2024-10-04 22:57 UTC, wfercanas commented on src/User/index.tsx
> +                key={index}
Don't use index as an index. Include an `id` in the interface of the prop so the user of the component is forced to pass it and we can use it as key as well.

2024-10-04 22:57 UTC, wfercanas commented on src/User/index.tsx
> +                      key={linkIndex}
The same change for keys in links and actions. Force the `id` to come through props.

2024-10-04 22:57 UTC, wfercanas commented on src/User/index.tsx
> +  menuSections: IUserSection[];
We can call this prop just `menu` and type it with `IUserMenu`. `IUserMenu` can be typed as `IMenuSection[]` which is the interface you currently have as `IUserSection`.

2024-10-04 22:57 UTC, wfercanas commented on src/User/index.tsx
> +    <>
Don't use a fragment here, instead use an StyledUser if you see the need to. This is because when rendering, the fragment disappears and both the stack and the menu get exposed to the layout of the parent.

For example, if the parent is a div that pretends to be the whole header, the header can have the rule `display: flex`. Since there is not element in between the header and the content of the User, the stack and the menu will start appearing one next to the other (and not one above the other).

![image](https://github.com/user-attachments/assets/1fb6c37b-9b6b-44da-adfa-3cbae5ff745a)

2024-10-05 00:11 UTC, cmarin001 commented on src/User/User.stories.tsx
> +        onClick: () => console.log("Logged out"),
solved

2024-10-05 00:11 UTC, cmarin001 commented on src/User/index.tsx
> +                key={index}
solved

2024-10-05 00:12 UTC, cmarin001 commented on src/User/index.tsx
> +                      key={linkIndex}
solved

2024-10-05 00:19 UTC, cmarin001 commented on src/User/index.tsx
> +  menuSections: IUserSection[];
solved

2024-10-05 00:32 UTC, cmarin001 commented on src/User/index.tsx
> +    <>
solved

2024-10-08 02:41 UTC, wfercanas approved these changes

2024-10-08 02:41 UTC, merged